# Road Hazard Data

In [1]:
cd "Stan's Datasets Notebooks"

[Errno 2] No such file or directory: "Stan's Datasets Notebooks"
/Users/connorheraty/Desktop/data-science/Stan's Datasets Notebooks

In [3]:
import pandas as pd
import numpy as np
import camelot
import os
import glob
import json
import re

In [4]:
lc_n_bridges = camelot.read_pdf('https://member.coach-net.com/members/pdfs/lowclearancebridgeinfo.pdf', pages='all')

lc_n_bridges

In [6]:
lc_n_bridges.export("./Raw POI Factory Datasets/Low Clearances and Bridges/lowclearancebridgeinfo.csv", f='csv')

In [7]:
lc_n_bridges[0]

In [8]:
lc_n_bridges[0].df

                                                   0 1 2
0
1               Low Clearance and Bridge Information
2  While it is our desire to provide the most acc...
3

In [9]:
os.remove('./Raw POI Factory Datasets/Low Clearances and Bridges/lowclearancebridgeinfo-page-1-table-1.csv')

In [10]:
os.chdir("./Raw POI Factory Datasets/Low Clearances and Bridges/")

In [11]:
extension = 'csv'
lc_n_bridges = [i for i in glob.glob('*.{}'.format(extension))]

In [12]:
lc_n_bridges_csv = pd.concat([pd.read_csv(f) for f in lc_n_bridges])

In [13]:
lc_n_bridges_csv.to_csv("lowclearanceandbridgeinfo.csv", index=False, encoding='utf-8-sig')

In [14]:
lc_n_bridges = pd.read_csv('lowclearanceandbridgeinfo.csv')

lc_n_bridges.head()

,State,HWY #,Location,Height,Inches,Posted,Height.1
0,OH,OH 100,Tiffin- 0.3 Mile North of OH 18,11.0,7.0,NaN,NaN
1,OH,OH 103,Willard- 1.4 Mile North of US 224,13.0,4.0,NaN,NaN
2,OH,OH 111 NB,Defiance- 0.7 Mile South of OH 424,11.0,11.0,NaN,NaN
3,OH,OH 111 SB,Defiance- 0.7 Mile South of OH 424,11.0,10.0,NaN,NaN
4,OH,OH 126,The Village of Indian Hills- 1.7 Miles East of...,12.0,9.0,NaN,NaN

In [15]:
filelist = glob.glob('lowclearancebridgeinfo-page-*')
for filename in filelist:
    os.remove(filename)

In [16]:
lc_n_bridges['Longitude'] = np.nan
lc_n_bridges['Latitude'] = np.nan

In [17]:
lc_n_bridges.head()

,State,HWY #,Location,Height,Inches,Posted,Height.1,Longitude,Latitude
0,OH,OH 100,Tiffin- 0.3 Mile North of OH 18,11.0,7.0,NaN,NaN,NaN,NaN
1,OH,OH 103,Willard- 1.4 Mile North of US 224,13.0,4.0,NaN,NaN,NaN,NaN
2,OH,OH 111 NB,Defiance- 0.7 Mile South of OH 424,11.0,11.0,NaN,NaN,NaN,NaN
3,OH,OH 111 SB,Defiance- 0.7 Mile South of OH 424,11.0,10.0,NaN,NaN,NaN,NaN
4,OH,OH 126,The Village of Indian Hills- 1.7 Miles East of...,12.0,9.0,NaN,NaN,NaN,NaN

In [18]:
lc_n_bridges = lc_n_bridges.rename(columns={'Height': 'Ft', 'Posted': 'Posted Ft', 'Height.1': 'Posted Inches'})

lc_n_bridges.head()

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
0,OH,OH 100,Tiffin- 0.3 Mile North of OH 18,11.0,7.0,NaN,NaN,NaN,NaN
1,OH,OH 103,Willard- 1.4 Mile North of US 224,13.0,4.0,NaN,NaN,NaN,NaN
2,OH,OH 111 NB,Defiance- 0.7 Mile South of OH 424,11.0,11.0,NaN,NaN,NaN,NaN
3,OH,OH 111 SB,Defiance- 0.7 Mile South of OH 424,11.0,10.0,NaN,NaN,NaN,NaN
4,OH,OH 126,The Village of Indian Hills- 1.7 Miles East of...,12.0,9.0,NaN,NaN,NaN,NaN

In [19]:
lc_n_bridges[lc_n_bridges['State'] == 'AL']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
414,AL,AL 1/US 31,Seale,13.0,0.0,NaN,NaN,NaN,NaN
415,AL,AL 10,Greenville,10.0,0.0,NaN,NaN,NaN,NaN
416,AL,AL 111,Wetumpka - at Coosa Rver Bridge,12.0,6.0,NaN,NaN,NaN,NaN
417,AL,AL 251,Ardmore,11.0,0.0,NaN,NaN,NaN,NaN
418,AL,AL 51,Opelika-South of Jct. I-85,13.0,4.0,NaN,NaN,NaN,NaN
419,AL,AL 53,"Ardmore-West, East of Jct I-65",10.0,8.0,NaN,NaN,NaN,NaN
420,AL,Local Road,"Nectar-1 mile east, Locust Fork River, covered...",9.0,0.0,NaN,NaN,NaN,NaN
421,AL,Swan Bridge Rd,Cleveland-1 mile west at Locust Fork River Bridge,13.0,0.0,NaN,NaN,NaN,NaN
422,AL,US 31,Montgomery - at Coosa River,13.0,4.0,NaN,NaN,NaN,NaN
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN
424,AL,US 98 WB,Spanish Fort - 0.3 miles west,13.0,6.0,NaN,NaN,NaN,NaN

In [20]:
lc_n_bridges[lc_n_bridges['Location'] == 'Mobile-Bankhead Tunnel']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN

In [21]:
lc_n_bridges.at[380,'Longitude'] = -88.030960

In [22]:
lc_n_bridges[lc_n_bridges['Location'] == 'Mobile-Bankhead Tunnel']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN

In [23]:
lc_n_bridges.at[380,'Latitude'] = 30.692998

In [24]:
lc_n_bridges[lc_n_bridges['Location'] == 'Mobile-Bankhead Tunnel']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN

In [25]:
lc_n_bridges.at[380,'Posted Ft'] = 12.0
lc_n_bridges.at[380,'Posted Inches'] = 0.0

lc_n_bridges[lc_n_bridges['State'] == 'AL']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
414,AL,AL 1/US 31,Seale,13.0,0.0,NaN,NaN,NaN,NaN
415,AL,AL 10,Greenville,10.0,0.0,NaN,NaN,NaN,NaN
416,AL,AL 111,Wetumpka - at Coosa Rver Bridge,12.0,6.0,NaN,NaN,NaN,NaN
417,AL,AL 251,Ardmore,11.0,0.0,NaN,NaN,NaN,NaN
418,AL,AL 51,Opelika-South of Jct. I-85,13.0,4.0,NaN,NaN,NaN,NaN
419,AL,AL 53,"Ardmore-West, East of Jct I-65",10.0,8.0,NaN,NaN,NaN,NaN
420,AL,Local Road,"Nectar-1 mile east, Locust Fork River, covered...",9.0,0.0,NaN,NaN,NaN,NaN
421,AL,Swan Bridge Rd,Cleveland-1 mile west at Locust Fork River Bridge,13.0,0.0,NaN,NaN,NaN,NaN
422,AL,US 31,Montgomery - at Coosa River,13.0,4.0,NaN,NaN,NaN,NaN
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN
424,AL,US 98 WB,Spanish Fort - 0.3 miles west,13.0,6.0,NaN,NaN,NaN,NaN

In [26]:
lc_n_bridges.at[381,'Longitude'] = -87.916574
lc_n_bridges.at[381,'Latitude'] = 30.666192

lc_n_bridges[lc_n_bridges['State'] == 'AL']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
414,AL,AL 1/US 31,Seale,13.0,0.0,NaN,NaN,NaN,NaN
415,AL,AL 10,Greenville,10.0,0.0,NaN,NaN,NaN,NaN
416,AL,AL 111,Wetumpka - at Coosa Rver Bridge,12.0,6.0,NaN,NaN,NaN,NaN
417,AL,AL 251,Ardmore,11.0,0.0,NaN,NaN,NaN,NaN
418,AL,AL 51,Opelika-South of Jct. I-85,13.0,4.0,NaN,NaN,NaN,NaN
419,AL,AL 53,"Ardmore-West, East of Jct I-65",10.0,8.0,NaN,NaN,NaN,NaN
420,AL,Local Road,"Nectar-1 mile east, Locust Fork River, covered...",9.0,0.0,NaN,NaN,NaN,NaN
421,AL,Swan Bridge Rd,Cleveland-1 mile west at Locust Fork River Bridge,13.0,0.0,NaN,NaN,NaN,NaN
422,AL,US 31,Montgomery - at Coosa River,13.0,4.0,NaN,NaN,NaN,NaN
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN
424,AL,US 98 WB,Spanish Fort - 0.3 miles west,13.0,6.0,NaN,NaN,NaN,NaN

In [27]:
lc_n_bridges = lc_n_bridges.append({'State': 'AL', 'HWY #': 'US 90', 
                                    'Location': 'Spanish Fort-Battleship Parkway', 
                                    'Ft': 13.0, 'Inches': 6.0, 'Posted Ft': np.nan, 
                                    'Posted Inches': np.nan, 'Longitude': -87.986697, 
                                    'Latitude': 30.678119}, ignore_index=True)

In [28]:
lc_n_bridges[lc_n_bridges['State'] == 'AL']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
414,AL,AL 1/US 31,Seale,13.0,0.0,NaN,NaN,NaN,NaN
415,AL,AL 10,Greenville,10.0,0.0,NaN,NaN,NaN,NaN
416,AL,AL 111,Wetumpka - at Coosa Rver Bridge,12.0,6.0,NaN,NaN,NaN,NaN
417,AL,AL 251,Ardmore,11.0,0.0,NaN,NaN,NaN,NaN
418,AL,AL 51,Opelika-South of Jct. I-85,13.0,4.0,NaN,NaN,NaN,NaN
419,AL,AL 53,"Ardmore-West, East of Jct I-65",10.0,8.0,NaN,NaN,NaN,NaN
420,AL,Local Road,"Nectar-1 mile east, Locust Fork River, covered...",9.0,0.0,NaN,NaN,NaN,NaN
421,AL,Swan Bridge Rd,Cleveland-1 mile west at Locust Fork River Bridge,13.0,0.0,NaN,NaN,NaN,NaN
422,AL,US 31,Montgomery - at Coosa River,13.0,4.0,NaN,NaN,NaN,NaN
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN
424,AL,US 98 WB,Spanish Fort - 0.3 miles west,13.0,6.0,NaN,NaN,NaN,NaN
998,AL,US 90,Spanish Fort-Battleship Parkway,13.0,6.0,NaN,NaN,-87.986697,30.678119

In [29]:
lc_n_bridges = lc_n_bridges.append({'State': 'AL', 'HWY #': 'Industrial Rd', 
                                    'Location': 'Jackson-Near River Rd', 
                                    'Ft': 11.0, 'Inches': 0.0, 'Posted Ft': np.nan, 
                                    'Posted Inches': np.nan, 'Longitude': -87.904922, 
                                    'Latitude': 31.495218}, ignore_index=True)

In [30]:
lc_n_bridges[lc_n_bridges['State'] == 'AL']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
414,AL,AL 1/US 31,Seale,13.0,0.0,NaN,NaN,NaN,NaN
415,AL,AL 10,Greenville,10.0,0.0,NaN,NaN,NaN,NaN
416,AL,AL 111,Wetumpka - at Coosa Rver Bridge,12.0,6.0,NaN,NaN,NaN,NaN
417,AL,AL 251,Ardmore,11.0,0.0,NaN,NaN,NaN,NaN
418,AL,AL 51,Opelika-South of Jct. I-85,13.0,4.0,NaN,NaN,NaN,NaN
419,AL,AL 53,"Ardmore-West, East of Jct I-65",10.0,8.0,NaN,NaN,NaN,NaN
420,AL,Local Road,"Nectar-1 mile east, Locust Fork River, covered...",9.0,0.0,NaN,NaN,NaN,NaN
421,AL,Swan Bridge Rd,Cleveland-1 mile west at Locust Fork River Bridge,13.0,0.0,NaN,NaN,NaN,NaN
422,AL,US 31,Montgomery - at Coosa River,13.0,4.0,NaN,NaN,NaN,NaN
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN
424,AL,US 98 WB,Spanish Fort - 0.3 miles west,13.0,6.0,NaN,NaN,NaN,NaN
998,AL,US 90,Spanish Fort-Battleship Parkway,13.0,6.0,NaN,NaN,-87.986697,30.678119
999,AL,Industrial Rd,Jackson-Near River Rd,11.0,0.0,NaN,NaN,-87.904922,31.495218

In [31]:
lc_n_bridges = lc_n_bridges.append({'State': 'AL', 'HWY #': 'County Rd 40', 
                                    'Location': 'Ozark - Jodie Parker Rd', 
                                    'Ft': 8.0, 'Inches': 0.0, 'Posted Ft': np.nan, 
                                    'Posted Inches': np.nan, 'Longitude': -85.659372, 
                                    'Latitude': 31.472883}, ignore_index=True)

In [32]:
lc_n_bridges[lc_n_bridges['State'] == 'AL']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
414,AL,AL 1/US 31,Seale,13.0,0.0,NaN,NaN,NaN,NaN
415,AL,AL 10,Greenville,10.0,0.0,NaN,NaN,NaN,NaN
416,AL,AL 111,Wetumpka - at Coosa Rver Bridge,12.0,6.0,NaN,NaN,NaN,NaN
417,AL,AL 251,Ardmore,11.0,0.0,NaN,NaN,NaN,NaN
418,AL,AL 51,Opelika-South of Jct. I-85,13.0,4.0,NaN,NaN,NaN,NaN
419,AL,AL 53,"Ardmore-West, East of Jct I-65",10.0,8.0,NaN,NaN,NaN,NaN
420,AL,Local Road,"Nectar-1 mile east, Locust Fork River, covered...",9.0,0.0,NaN,NaN,NaN,NaN
421,AL,Swan Bridge Rd,Cleveland-1 mile west at Locust Fork River Bridge,13.0,0.0,NaN,NaN,NaN,NaN
422,AL,US 31,Montgomery - at Coosa River,13.0,4.0,NaN,NaN,NaN,NaN
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN
424,AL,US 98 WB,Spanish Fort - 0.3 miles west,13.0,6.0,NaN,NaN,NaN,NaN
998,AL,US 90,Spanish Fort-Battleship Parkway,13.0,6.0,NaN,NaN,-87.986697,30.678119
999,AL,Industrial Rd,Jackson-Near River Rd,11.0,0.0,NaN,NaN,-87.904922,31.495218
1000,AL,County Rd 40,Ozark - Jodie Parker Rd,8.0,0.0,NaN,NaN,-85.659372,31.472883

In [33]:
lc_n_bridges.at[372,'Posted Ft'] = 10.0
lc_n_bridges.at[372,'Posted Inches'] = 0.0
lc_n_bridges.at[372,'Longitude'] = -86.627767
lc_n_bridges.at[372,'Latitude'] = 31.829544

In [34]:
lc_n_bridges[lc_n_bridges['State'] == 'AL']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
414,AL,AL 1/US 31,Seale,13.0,0.0,NaN,NaN,NaN,NaN
415,AL,AL 10,Greenville,10.0,0.0,NaN,NaN,NaN,NaN
416,AL,AL 111,Wetumpka - at Coosa Rver Bridge,12.0,6.0,NaN,NaN,NaN,NaN
417,AL,AL 251,Ardmore,11.0,0.0,NaN,NaN,NaN,NaN
418,AL,AL 51,Opelika-South of Jct. I-85,13.0,4.0,NaN,NaN,NaN,NaN
419,AL,AL 53,"Ardmore-West, East of Jct I-65",10.0,8.0,NaN,NaN,NaN,NaN
420,AL,Local Road,"Nectar-1 mile east, Locust Fork River, covered...",9.0,0.0,NaN,NaN,NaN,NaN
421,AL,Swan Bridge Rd,Cleveland-1 mile west at Locust Fork River Bridge,13.0,0.0,NaN,NaN,NaN,NaN
422,AL,US 31,Montgomery - at Coosa River,13.0,4.0,NaN,NaN,NaN,NaN
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN
424,AL,US 98 WB,Spanish Fort - 0.3 miles west,13.0,6.0,NaN,NaN,NaN,NaN
998,AL,US 90,Spanish Fort-Battleship Parkway,13.0,6.0,NaN,NaN,-87.986697,30.678119
999,AL,Industrial Rd,Jackson-Near River Rd,11.0,0.0,NaN,NaN,-87.904922,31.495218
1000,AL,County Rd 40,Ozark - Jodie Parker Rd,8.0,0.0,NaN,NaN,-85.659372,31.472883

In [35]:
lc_n_bridges.at[371, 'HWY #'] = 'County Rd 30'
lc_n_bridges.at[371, 'Location'] = 'Seale - Carver Rd/30 under Hwy 431'
lc_n_bridges.at[371,'Longitude'] = -85.178744
lc_n_bridges.at[371,'Latitude'] = 32.294212

In [36]:
lc_n_bridges[lc_n_bridges['State'] == 'AL']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
414,AL,AL 1/US 31,Seale,13.0,0.0,NaN,NaN,NaN,NaN
415,AL,AL 10,Greenville,10.0,0.0,NaN,NaN,NaN,NaN
416,AL,AL 111,Wetumpka - at Coosa Rver Bridge,12.0,6.0,NaN,NaN,NaN,NaN
417,AL,AL 251,Ardmore,11.0,0.0,NaN,NaN,NaN,NaN
418,AL,AL 51,Opelika-South of Jct. I-85,13.0,4.0,NaN,NaN,NaN,NaN
419,AL,AL 53,"Ardmore-West, East of Jct I-65",10.0,8.0,NaN,NaN,NaN,NaN
420,AL,Local Road,"Nectar-1 mile east, Locust Fork River, covered...",9.0,0.0,NaN,NaN,NaN,NaN
421,AL,Swan Bridge Rd,Cleveland-1 mile west at Locust Fork River Bridge,13.0,0.0,NaN,NaN,NaN,NaN
422,AL,US 31,Montgomery - at Coosa River,13.0,4.0,NaN,NaN,NaN,NaN
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN
424,AL,US 98 WB,Spanish Fort - 0.3 miles west,13.0,6.0,NaN,NaN,NaN,NaN
998,AL,US 90,Spanish Fort-Battleship Parkway,13.0,6.0,NaN,NaN,-87.986697,30.678119
999,AL,Industrial Rd,Jackson-Near River Rd,11.0,0.0,NaN,NaN,-87.904922,31.495218
1000,AL,County Rd 40,Ozark - Jodie Parker Rd,8.0,0.0,NaN,NaN,-85.659372,31.472883

In [37]:
lc_n_bridges = lc_n_bridges.append({'State': 'AL', 'HWY #': '2nd Ave', 
                                    'Location': 'Phenix - S. Railroad St/2nd Ave', 
                                    'Ft': 8.0, 'Inches': 0.0, 'Posted Ft': np.nan, 
                                    'Posted Inches': np.nan, 'Longitude': -84.996882, 
                                    'Latitude': 32.477346}, ignore_index=True)

In [38]:
lc_n_bridges = lc_n_bridges.append({'State': 'AL', 'HWY #': '4th Ave', 
                                    'Location': 'Phenix - 1803 4th Ave', 
                                    'Ft': 8.0, 'Inches': 0.0, 'Posted Ft': np.nan, 
                                    'Posted Inches': np.nan, 'Longitude': -84.998566, 
                                    'Latitude': 32.477232}, ignore_index=True)

In [39]:
lc_n_bridges[lc_n_bridges['State'] == 'AL']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
414,AL,AL 1/US 31,Seale,13.0,0.0,NaN,NaN,NaN,NaN
415,AL,AL 10,Greenville,10.0,0.0,NaN,NaN,NaN,NaN
416,AL,AL 111,Wetumpka - at Coosa Rver Bridge,12.0,6.0,NaN,NaN,NaN,NaN
417,AL,AL 251,Ardmore,11.0,0.0,NaN,NaN,NaN,NaN
418,AL,AL 51,Opelika-South of Jct. I-85,13.0,4.0,NaN,NaN,NaN,NaN
419,AL,AL 53,"Ardmore-West, East of Jct I-65",10.0,8.0,NaN,NaN,NaN,NaN
420,AL,Local Road,"Nectar-1 mile east, Locust Fork River, covered...",9.0,0.0,NaN,NaN,NaN,NaN
421,AL,Swan Bridge Rd,Cleveland-1 mile west at Locust Fork River Bridge,13.0,0.0,NaN,NaN,NaN,NaN
422,AL,US 31,Montgomery - at Coosa River,13.0,4.0,NaN,NaN,NaN,NaN
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN
424,AL,US 98 WB,Spanish Fort - 0.3 miles west,13.0,6.0,NaN,NaN,NaN,NaN
998,AL,US 90,Spanish Fort-Battleship Parkway,13.0,6.0,NaN,NaN,-87.986697,30.678119
999,AL,Industrial Rd,Jackson-Near River Rd,11.0,0.0,NaN,NaN,-87.904922,31.495218
1000,AL,County Rd 40,Ozark - Jodie Parker Rd,8.0,0.0,NaN,NaN,-85.659372,31.472883
1001,AL,2nd Ave,Phenix - S. Railroad St/2nd Ave,8.0,0.0,NaN,NaN,-84.996882,32.477346
1002,AL,4th Ave,Phenix - 1803 4th Ave,8.0,0.0,NaN,NaN,-84.998566,32.477232

In [40]:
lc_n_bridges.at[373,'Posted Ft'] = 12.0
lc_n_bridges.at[373,'Posted Inches'] = 6.0
lc_n_bridges.at[373,'Longitude'] = -86.207025
lc_n_bridges.at[373,'Latitude'] = 32.538458

In [41]:
lc_n_bridges[lc_n_bridges['State'] == 'AL']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
414,AL,AL 1/US 31,Seale,13.0,0.0,NaN,NaN,NaN,NaN
415,AL,AL 10,Greenville,10.0,0.0,NaN,NaN,NaN,NaN
416,AL,AL 111,Wetumpka - at Coosa Rver Bridge,12.0,6.0,NaN,NaN,NaN,NaN
417,AL,AL 251,Ardmore,11.0,0.0,NaN,NaN,NaN,NaN
418,AL,AL 51,Opelika-South of Jct. I-85,13.0,4.0,NaN,NaN,NaN,NaN
419,AL,AL 53,"Ardmore-West, East of Jct I-65",10.0,8.0,NaN,NaN,NaN,NaN
420,AL,Local Road,"Nectar-1 mile east, Locust Fork River, covered...",9.0,0.0,NaN,NaN,NaN,NaN
421,AL,Swan Bridge Rd,Cleveland-1 mile west at Locust Fork River Bridge,13.0,0.0,NaN,NaN,NaN,NaN
422,AL,US 31,Montgomery - at Coosa River,13.0,4.0,NaN,NaN,NaN,NaN
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN
424,AL,US 98 WB,Spanish Fort - 0.3 miles west,13.0,6.0,NaN,NaN,NaN,NaN
998,AL,US 90,Spanish Fort-Battleship Parkway,13.0,6.0,NaN,NaN,-87.986697,30.678119
999,AL,Industrial Rd,Jackson-Near River Rd,11.0,0.0,NaN,NaN,-87.904922,31.495218
1000,AL,County Rd 40,Ozark - Jodie Parker Rd,8.0,0.0,NaN,NaN,-85.659372,31.472883
1001,AL,2nd Ave,Phenix - S. Railroad St/2nd Ave,8.0,0.0,NaN,NaN,-84.996882,32.477346
1002,AL,4th Ave,Phenix - 1803 4th Ave,8.0,0.0,NaN,NaN,-84.998566,32.477232

In [42]:
lc_n_bridges = lc_n_bridges.append({'State': 'AL', 'HWY #': 'County Rd 18', 
                                    'Location': 'Forkland', 
                                    'Ft': 8.0, 'Inches': 0.0, 'Posted Ft': np.nan, 
                                    'Posted Inches': np.nan, 'Longitude': -87.830738, 
                                    'Latitude': 32.549558}, ignore_index=True)

In [43]:
lc_n_bridges[lc_n_bridges['State'] == 'AL']

,State,HWY #,Location,Ft,Inches,Posted Ft,Posted Inches,Longitude,Latitude
414,AL,AL 1/US 31,Seale,13.0,0.0,NaN,NaN,NaN,NaN
415,AL,AL 10,Greenville,10.0,0.0,NaN,NaN,NaN,NaN
416,AL,AL 111,Wetumpka - at Coosa Rver Bridge,12.0,6.0,NaN,NaN,NaN,NaN
417,AL,AL 251,Ardmore,11.0,0.0,NaN,NaN,NaN,NaN
418,AL,AL 51,Opelika-South of Jct. I-85,13.0,4.0,NaN,NaN,NaN,NaN
419,AL,AL 53,"Ardmore-West, East of Jct I-65",10.0,8.0,NaN,NaN,NaN,NaN
420,AL,Local Road,"Nectar-1 mile east, Locust Fork River, covered...",9.0,0.0,NaN,NaN,NaN,NaN
421,AL,Swan Bridge Rd,Cleveland-1 mile west at Locust Fork River Bridge,13.0,0.0,NaN,NaN,NaN,NaN
422,AL,US 31,Montgomery - at Coosa River,13.0,4.0,NaN,NaN,NaN,NaN
423,AL,US 90,Mobile-Bankhead Tunnel,12.0,0.0,NaN,NaN,NaN,NaN
424,AL,US 98 WB,Spanish Fort - 0.3 miles west,13.0,6.0,NaN,NaN,NaN,NaN
998,AL,US 90,Spanish Fort-Battleship Parkway,13.0,6.0,NaN,NaN,-87.986697,30.678119
999,AL,Industrial Rd,Jackson-Near River Rd,11.0,0.0,NaN,NaN,-87.904922,31.495218
1000,AL,County Rd 40,Ozark - Jodie Parker Rd,8.0,0.0,NaN,NaN,-85.659372,31.472883
1001,AL,2nd Ave,Phenix - S. Railroad St/2nd Ave,8.0,0.0,NaN,NaN,-84.996882,32.477346
1002,AL,4th Ave,Phenix - 1803 4th Ave,8.0,0.0,NaN,NaN,-84.998566,32.477232
1003,AL,County Rd 18,Forkland,8.0,0.0,NaN,NaN,-87.830738,32.549558

# Scraping with Selenium

In [44]:
!pip install selenium

Requirement already satisfied: selenium in /anaconda3/lib/python3.7/site-packages (3.141.0)
Requirement already satisfied: urllib3 in /anaconda3/lib/python3.7/site-packages (from selenium) (1.24.3)

In [49]:
with open('st_credentials.json') as creds:    
    credentials = json.load(creds)

In [50]:
import time
from selenium import webdriver

# driver = webdriver.Chrome('/home/seek/Documents/GitHub/chromedriver')  # Optional argument, if not specified will search path.
# driver.get('http://www.google.com/');
# time.sleep(5) # Let the user actually see something!
# search_box = driver.find_element_by_name('q')
# search_box.send_keys('ChromeDriver')
# search_box.submit()
# time.sleep(5) # Let the user actually see something!
# driver.quit()

In [51]:
# driver = webdriver.Chrome()
# driver.get("http://www.python.org")
# assert "Python" in driver.title
# elem = driver.find_element_by_name("q")
# elem.clear()
# elem.send_keys("pycon")
# elem.send_keys(Keys.RETURN)
# assert "No results found." not in driver.page_source
# driver.close()

In [54]:
ls

POI Datasets.ipynb        Road Hazards.ipynb        st_credentials.json
Raw POI Factory Datasets/ chromedriver*

In [82]:
driver = webdriver.Chrome()

driver.get("https://www.surfacetracks.com/amember/login")

user_element = driver.find_element_by_name("amember_login")
pass_element = driver.find_element_by_name("amember_pass")


user_element.send_keys(credentials['amember_login'])
pass_element.send_keys(credentials['amember_pass'])

driver.find_element_by_xpath("//input[@value='Login']").click()

WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

In [ ]:
driver.get('https://www.surfacetracks.com/plus/get-feature.php?id=107368')

In [67]:
driver = webdriver.Chrome(executable_path="/Users/connorheraty/Desktop/data-science/Stan\'s\ Datasets\ Notebooks//chromedriver.exe")

WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

In [78]:
from selenium import webdriver

PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
DRIVER_BIN = os.path.join(PROJECT_ROOT, "chromedriver.exe")

browser = webdriver.Chrome(executable_path = DRIVER_BIN)
browser.get('http://www.baidu.com/')

NameError: name '__file__' is not defined

In [72]:
PROJECT_ROOT = os.path.abspath(os.path.dirname('chromedriver.exe'))

In [79]:
DRIVER_BIN = os.path.join(PROJECT_ROOT, "chromedriver.exe")

In [81]:
DRIVER_BIN

"/Users/connorheraty/Desktop/data-science/Stan's Datasets Notebooks/chromedriver.exe"

In [80]:
browser = webdriver.Chrome(executable_path = DRIVER_BIN)

WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home